<a href="https://colab.research.google.com/github/zidanesouza/SBSPS-Challenge-4551-Sentiment-Analysis-of-COVID-19-Tweets-Visualization-Dashboard/blob/master/ITSC_expt6_17CO19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
input = np.array([[2,0,1],[2,-2,1],[1,-2,-1]])
print('Training Inputs are:')
print(input)
weight = np.array([1,0,1])
print('Initial Weights are:')
print(weight)
d=np.array([-1,1,1])
c=0.5
    
j=0
for i in input:
    print("c=",c)
    net=np.dot(i,weight)
    print("net=",net)
    temp=c*(d[j]-net)
    print("temp=",temp)
    del_w=np.dot(temp,i)
    print("delw=",del_w)
    weight=weight+del_w
    j=j+1
    print("j=",j)
    print("updated weight is",weight)


Training Inputs are:
[[ 2  0  1]
 [ 2 -2  1]
 [ 1 -2 -1]]
Initial Weights are:
[1 0 1]
c= 0.5
net= 3
temp= -2.0
delw= [-4.  0. -2.]
j= 1
updated weight is [-3.  0. -1.]
c= 0.5
net= -7.0
temp= 4.0
delw= [ 8. -8.  4.]
j= 2
updated weight is [ 5. -8.  3.]
c= 0.5
net= 18.0
temp= -8.5
delw= [-8.5 17.   8.5]
j= 3
updated weight is [-3.5  9.  11.5]
